### ISSUE TITLE
Keeping docs complete and up-to-date

### ISSUE THREAD

**Issue by EndPositive** [secureCodeBox/documentation#122]
The documentation is in some place very out of date or incomplete. To give a few examples:

- [ ] Incomplete:
* [automatically-repeating-scans.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/how-tos/automatically-repeating-scans.md) #127 
* [scanning-web-applications.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/how-tos/scanning-web-applications.md) #130 
* [conventions.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/contributing/conventions.md)

- [x] Out-of-date #126 :
*  [integrating-a-scanner.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/contributing/integrating-a-scanner.md) incorrect tree
* [integrating-a-hook.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/contributing/integrating-a-hook.md) incorrect tree
*  [scanners.md](https://github.com/secureCodeBox/documentation/blob/9acdf4004b36fbf63c55f64b19811b06ba4ff7ed/docs/scanners.md) does not include nuclei, whatweb, typo3scan
 
What are the guidelines concerning keeping the documentation up-to-date? How is decided what topics may be published as incomplete? How are newly implemented features required to update the docs too?

This issue is in no way a shame and blame post, but I'd just like to get some more insight into how this process is currently maintained.

Maybe it would be a good idea to make issues for the currently incorrect documentation so that contributors can pick them up more easily.

**Comment by fuhrmeistery** [comment]
Good point! We need to address this.

**Comment by malexmave** [comment]
Open todos from the review by @Ilyesbdlala @J12934 and me, the following points were still open for the docs, still in German because it came from my notes:

- [ ] Operator Configuration Options: Generelle Infos wie man die Options an den Operator kriegt einfügen. Dafür kann man auch die Funktion der docs nutzen um einen Dateinamen anzugeben, wie beim nmap scan im „starting your first scan"
- [ ] Operator Configuration Options: Tabelle mit gesamten Konfigurationsoptionen verlinken
- [ ] Allgemein: Copy-paste issues mit linebreaks resolven - docosaurus update?
- [ ] Install SCB Scanner: Sektion entschlacken: Ein Beispiel-Installations-Kommando geben und auf Liste der Scanner verlinken (Scanner Overview in der sidebar)
- [ ] Install demo targets: Liste der demo targets ist ebenfalls outdated
- [ ] Neue Sektion: Upgrading (CRD upgrades, also upgrade scanners, all namespaces separately, ...)
- [ ] Troubleshooting von der Installation-Seite auf die Troubleshooting-Seite ziehen (aktuell redundant)

**Comment by malexmave** [comment]
I have created lots of issues for the individual scanners and other pages that need a  read. See the "maintainance" tag in the list of issues.

**Comment by sanmai-NL** [comment]
From blog posts, I have gleaned quite some info about SCB's architecture. However, checking the official docs then suggests there is hardly architectural documentation. I think an effort to simply curate all you already have would pay of substantially.

**Comment by malexmave** [comment]
We have created a number of more specific issues  based on this issue to track different sub-points (among others, secureCodeBox/documentation#207 secureCodeBox/documentation#208 secureCodeBox/documentation#209 secureCodeBox/secureCodeBox#1912, plus updates to some existing issues), so I'll close this issue. Thank you again for your input.
